apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: consumer